default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: makeabox_development

test:
  <<: *default
  database: makeabox_test

production:
  <<: *default
  database: makeabox_production
  username: makeabox
  password: <%= ENV['MAKEABOX_DATABASE_PASSWORD'] %>
